### ISSUE TITLE
create entity

### ISSUE THREAD

**Issue by kkjiyeon** [hometown-market/HomeTown_Market#16]
user, product, like

**Comment by Kim-S-Min** [comment]
Project 진행 사항에 1차 종료로 되어있는데 pr이 보이지 않습니다.
혹시 진행이 된 사항이라면 pr 연결해주시고 이미 merge된 사항이라면 코멘트 부탁드립니다!

**Comment by kkjiyeon** [comment]
issue#13에 merge 되었습니다!
