### ISSUE TITLE
Create Project folder

### ISSUE THREAD

**Issue by Kim-S-Min** [hometown-market/HomeTown_Market#2]

**Comment by Kim-S-Min** [comment]
backend_develop로 진행되는 것이 아닌 frontend와 backend 폴더가 존재하는 "develop"브랜치로 개발이 진행됩니다.
develop 브랜치에서 feature 브랜치들을 만들어서 사용할 때는 바로 merge하면 안되고 pull request에 꼭 경로를 설정하고 리뷰요청을 해야 합니다.(중요)
프로젝트 생성 이후 진행 되는 브랜치는 "Issue#n-기능명"으로 진행해주시면 됩니다.

확인 후 코멘트 부탁드립니다

**Comment by kkjiyeon** [comment]
> backend_develop로 진행되는 것이 아닌 frontend와 backend 폴더가 존재하는 "develop"브랜치�로 개발이 진행됩니다. develop 브랜치에서 feature 브랜치들을 만들어서 사용할 때는 바로 merge하면 안되고 pull request에 꼭 경로를 설정하고 리뷰요청을 해야 합니다.(중요) 프로젝트 생성 이후 진행 되는 브랜치는 "Issue#n-기능명"으로 진행해주시면 됩니다.
> 
> 확인 후 코멘트 부탁드립니다

네 알겠습니다 확인했습니다!

**Comment by suker80** [comment]
넵 바꿔넣겠습니당
